# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Allow 5 seconds for commands executed by Starship
command_timeout = 5000

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[hostname]
format = '[$hostname]($style) in '

[erlang]
symbol = "ⓔ "

[lua]
detect_folders = []

[nodejs]
style = 'bold green'
symbol = '⬢ '

[pulumi]
symbol = "🧊 "
