# Allow 5 seconds for commands executed by Starship
command_timeout = 5000

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[directory]
truncation_length = 2
truncation_symbol = '…/'

[hostname]
format = '[$hostname]($style) in '
ssh_only = false
style = 'green bold'

[erlang]
symbol = "ⓔ "

[lua]
detect_folders = []

[nodejs]
style = 'bold green'
symbol = '⬢ '

[pulumi]
symbol = "🧊 "

[username]
format = '[$user]($style) at '
show_always = true
