command_timeout = 5000

[aws]
disabled = true

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[directory]
disabled = false
style = "bold blue"
truncate_to_repo = true
truncation_length = 3
truncation_symbol = '…/'

[docker_context]
disabled = false
format = "[\\($symbol$context\\)]($style) "

[elixir]
disabled = false
format = "[\\($symbol$version \\(OTP $otp_version\\)\\)]($style) "

[erlang]
disabled = false
format = "[\\($symbol$version\\)]($style) "
symbol = "ⓔ "

[git_branch]
disabled = false
style = "bold #6c71c4"

[golang]
disabled = false
format = "[\\($symbol$version\\)]($style) "
style = "bold cyan"

[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = true
style = "bold purple"
trim_at = '.'

[lua]
detect_folders = []
disabled = false
format = "[\\($symbol$version\\)]($style) "

[nodejs]
disabled = false
format = "[\\($symbol$version\\)]($style) "
symbol = "[⬢](bold green) "

[package]
disabled = true

[python]
disabled = false
format = "[\\($symbol$version( \\($virtualenv\\))\\)]($style) "
style = "bold #cb4b16"

[pulumi]
symbol = "🧊 "

[ruby]
disabled = false
format = "[\\($symbol$version\\)]($style) "

[rust]
disabled = false
format = "[\\($symbol$version\\)]($style) "

[terraform]
disabled = false
format = "[\\($symbol$workspace\\)]($style) "

[username]
disabled = false
format = "[$user]($style) in "
show_always = false
style_root = "bold red"
style_user = "bold #cb4b16"
