#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091,SC2034,SC2155
if ((BASH_VERSINFO[0] > 3)); then
    shopt -s autocd
    shopt -s cdspell
    shopt -s dirspell
    shopt -s globstar
fi

# Functions to help us manage paths.  Second argument is the name of the
# path variable to be modified (default: PATH).
# Taken from: https://www.linuxfromscratch.org/blfs/view/svn/postlfs/profile.html
path_remove () {
    local IFS=':'
    local NEWPATH
    local DIR
    local PATHVARIABLE=${2:-PATH}
    for DIR in ${!PATHVARIABLE}; do
        if [ "$DIR" != "$1" ]; then
            NEWPATH=${NEWPATH:+$NEWPATH:}$DIR
        fi
    done
    export "$PATHVARIABLE"="$NEWPATH"
}

path_prepend () {
    path_remove "$1" "$2"
    local PATHVARIABLE=${2:-PATH}
    export "$PATHVARIABLE"="$1${!PATHVARIABLE:+:${!PATHVARIABLE}}"
}

path_append () {
    path_remove "$1" "$2"
    local PATHVARIABLE=${2:-PATH}
    export "$PATHVARIABLE"="${!PATHVARIABLE:+${!PATHVARIABLE}:}$1"
}

# Check for /usr/local/sbin in PATH
if [[ -d "/usr/local/sbin" ]]; then
    path_prepend "/usr/local/sbin"
fi

# Check for /usr/local/bin in PATH
if [[ -d "/usr/local/bin" ]]; then
    path_prepend "/usr/local/bin"
fi

if [[ -e "/opt/homebrew/bin/brew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -e "/usr/local/bin/brew" ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi

# Import files from $HOME/.bashrc.d
if [[ -d "$HOME/.bashrc.d" ]]; then
    for config in "$HOME"/.bashrc.d/**/*.bash; do
        [[ -r "$config" ]] || continue
        source "$config"
    done
    unset -v config
fi

# Append to the history file, don't overwrite it
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=50000

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=erasedups:ignoreboth

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history"

# Useful timestamp format
HISTTIMEFORMAT='%F %T '

# Check the window size after each command and, if necessary,
# Update the values of LINES and COLUMNS.
shopt -s checkwinsize

# macOS settings
if [[ -v HOMEBREW_BASE ]]; then
    # Set Homebrew Cask default Applications directory
    export HOMEBREW_CASK_OPTS="--appdir=~/Applications"
    # Enable bash-completion with Homebrew
    export BASH_COMPLETION_COMPAT_DIR="$HOMEBREW_BASE/etc/bash_completion.d"
    if [[ -f "$HOMEBREW_BASE/etc/profile.d/bash_completion.sh" ]]; then
        source "$HOMEBREW_BASE/etc/profile.d/bash_completion.sh"
    fi
fi

# Prepend $HOME/.local/bin to PATH
if [[ -d "$HOME/.local/bin" ]]; then
    path_prepend "$HOME/.local/bin"
fi

# macOS curl config
if [[ "$OSTYPE" == darwin* ]]; then
    export CURL_SSL_BACKEND=secure-transport
fi

# Set EDITOR
if command -v code >/dev/null 2>&1 && [[ ! -v SSH_CONNECTION ]]; then
    export EDITOR="code"
else
    export EDITOR="vim"
fi

# Enable pipx
if command -v pipx >/dev/null 2>&1; then
    eval "$(register-python-argcomplete pipx)"
fi

# Enable Starship
if command -v starship >/dev/null 2>&1; then
    starship_precmd_user_func="set_win_title"
    eval "$(starship init bash)"
else
    export PROMPT_COMMAND=set_win_title
    export PROMPT_DIRTRIM=1
    export PS1="\n\u@\h: \w\n\\$ \[$(tput sgr0)\]"
fi

if command -v direnv >/dev/null 2>&1; then
    eval "$(direnv hook bash)"
fi

# iTerm2 shell integration
if [[ -e "$HOME/.iterm2_shell_integration.bash" ]]; then
    source "$HOME/.iterm2_shell_integration.bash"
fi
