HISTSIZE=8192
SAVEHIST=8192
HISTFILE="$HOME/.zsh_history"
HISTORY_IGNORE="(bg|clear|env|exit|fg|history|ls|pwd)"

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt EXTENDED_HISTORY
