#!/usr/bin/env sh
if [ $# -eq 0 ]; then
    printf "Missing volume path. Exiting.\n"
    exit 1
fi

VOLUME_PATH="$1"

if [ ! -d "$VOLUME_PATH" ]; then
    printf "Volume does not appear to be mounted. Exiting.\n"
    exit 1
fi

# Disable Spotlight indexing
printf "\nDisabling Spotlight indexing on volume: %s\n" "$VOLUME_PATH"
sudo mdutil -i off -d "$VOLUME_PATH"
printf "\nAdding /.metadata_never_index file to volume: %s\n" "$VOLUME_PATH"
sudo touch "$VOLUME_PATH/.metadata_never_index"

# Show Spotlight indexing status
printf "\nSpotlight indexing status for volume: %s\n" "$VOLUME_PATH"
mdutil -s "$VOLUME_PATH"

exit 0
