#!/usr/bin/env sh
# shellcheck shell=sh
if [ -x /opt/homebrew/bin/mactop ]; then
    sudo chown root:wheel "$(/opt/homebrew/bin/brew --prefix mactop)"/bin/mactop
    sudo chmod 4555 "$(/opt/homebrew/bin/brew --prefix mactop)"/bin/mactop
elif [ -x /usr/local/bin/mactop ]; then
    sudo chown root:wheel "$(/usr/local/bin/brew --prefix mactop)"/bin/mactop
    sudo chmod 4555 "$(/usr/local/bin/brew --prefix mactop)"/bin/mactop
else
    printf "Cannot find mactop in PATH. Exiting…\n"
fi
