#!/usr/bin/env sh
# shellcheck shell=sh
if [ -x /opt/homebrew/bin/htop ]; then
    sudo sh -c '
    chown root:wheel "$(/opt/homebrew/bin/brew --prefix htop)"/bin/htop
    chmod 4555 "$(/opt/homebrew/bin/brew --prefix htop)"/bin/htop
    '
else
    printf "Cannot find htop in /opt/homebrew/bin. Exiting…\n"
fi
