#!/usr/bin/env python3

import os


def main():
    """
    Program to demonstrate how to obtain the current value of the CPU temperature.
    """
    cpu_temp = get_cpu_temp()
    print(f"CPU temperature: {cpu_temp:.2f}ºC ({((cpu_temp * 1.8) + 32):.2f}ºF)")


def get_cpu_temp():
    """
    Obtains the current value of the CPU temperature.
    :returns: Current value of the CPU temperature if successful, zero value otherwise.
    :rtype: float
    """
    # Initialize the result.
    result = 0.0
    # The first line in this file holds the CPU temperature as an integer times 1000.
    # Read the first line and remove the newline character at the end of the string.
    if os.path.isfile("/sys/class/thermal/thermal_zone0/temp"):
        with open("/sys/class/thermal/thermal_zone0/temp") as f:
            line = f.readline().strip()
        # Test if the string is an integer as expected.
        if line.isdigit():
            # Convert the string with the CPU temperature to a float in degrees Celsius.
            result = float(line) / 1000
    # Give the result back to the caller.
    return result


if __name__ == "__main__":
    main()
