#!/usr/bin/env sh
# Set computer name
if [ $# -ne 2 ]; then
    echo "Missing computer name and host name. Exiting."
    exit 1
elif [ "$1" = "" ]; then
    echo "Missing computer name. Exiting."
    exit 1
elif [ "$2" = "" ]; then
    echo "Missing host name. Exiting."
    exit 1
fi
COMPUTER_NAME="$1"
HOST_NAME=$(echo "$2" | tr '[:upper:]' '[:lower:]')
sudo scutil --set ComputerName "$COMPUTER_NAME"
sudo scutil --set HostName "$HOST_NAME"
sudo scutil --set LocalHostName "$HOST_NAME"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$COMPUTER_NAME"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server Workgroup -string "SEALDOG"

# Configure Dock
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0.125
defaults write com.apple.dock autohide-time-modifier -float 0.5
defaults write com.apple.dock mineffect -string "scale"
defaults write com.apple.dock minimize-to-application -bool true
defaults write com.apple.dock orientation -string "left"
defaults write com.apple.dock show-recents -bool false
defaults write com.apple.dock showhidden -bool true
defaults write com.apple.dock tilesize -int 48
killall Dock

# Configure Finder
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy kind" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 75" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 48" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:textSize 11" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy kind" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 75" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 48" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:textSize 11" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy kind" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 75" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 48" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:textSize 11" ~/Library/Preferences/com.apple.finder.plist
defaults write com.apple.finder _FXSortFoldersFirst -bool true
defaults write com.apple.finder FXArrangeGroupViewBy -string "Kind"
defaults write com.apple.finder FXDefaultSearchScope -string "SCev"
defaults write com.apple.finder FXPreferredGroupBy -string "Name"
defaults write com.apple.finder FXPreferredViewStyle -string "icnv"
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowPathbar -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false
defaults write com.apple.finder ShowStatusBar -bool true
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.universalaccess showWindowTitlebarIcons -bool true
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
defaults write NSGlobalDomain NSRecentDocumentsLimit -int 0
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1
killall Finder

# Configure Safari
defaults write com.apple.Safari "ShowFavoritesBar-v2" -bool true
defaults write com.apple.Safari "WebKitPreferences.invisibleMediaAutoplayNotPermitted" -bool true
defaults write com.apple.Safari "WebKitPreferences.minimumFontSize" -int 13
defaults write com.apple.Safari "WebKitPreferences.tabFocusesLinks" -bool true
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false
defaults write com.apple.Safari DownloadsClearingPolicy -int 2
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
defaults write com.apple.Safari OpenNewTabsInFront -bool true
defaults write com.apple.Safari SearchProviderShortName -string "DuckDuckGo"
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true
defaults write com.apple.Safari ShowOverlayStatusBar -bool true
defaults write com.apple.Safari WebKitMediaPlaybackAllowsInline -bool false
defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
defaults write com.apple.Safari.SandboxBroker "ShowFavoritesBar-v2" -bool true
defaults write com.apple.Safari.SandboxBroker "WebKitPreferences.invisibleMediaAutoplayNotPermitted" -bool true
defaults write com.apple.Safari.SandboxBroker "WebKitPreferences.minimumFontSize" -int 13
defaults write com.apple.Safari.SandboxBroker "WebKitPreferences.tabFocusesLinks" -bool true
defaults write com.apple.Safari.SandboxBroker AutoFillCreditCardData -bool false
defaults write com.apple.Safari.SandboxBroker AutoFillFromAddressBook -bool false
defaults write com.apple.Safari.SandboxBroker AutoFillMiscellaneousForms -bool false
defaults write com.apple.Safari.SandboxBroker AutoFillPasswords -bool false
defaults write com.apple.Safari.SandboxBroker AutoOpenSafeDownloads -bool false
defaults write com.apple.Safari.SandboxBroker com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false
defaults write com.apple.Safari.SandboxBroker DownloadsClearingPolicy -int 2
defaults write com.apple.Safari.SandboxBroker IncludeDevelopMenu -bool true
defaults write com.apple.Safari.SandboxBroker IncludeDevelopMenu -bool true
defaults write com.apple.Safari.SandboxBroker IncludeInternalDebugMenu -bool true
defaults write com.apple.Safari.SandboxBroker OpenNewTabsInFront -bool true
defaults write com.apple.Safari.SandboxBroker SearchProviderShortName -string "DuckDuckGo"
defaults write com.apple.Safari.SandboxBroker ShowDevelopMenu -bool true
defaults write com.apple.Safari.SandboxBroker ShowFullURLInSmartSearchField -bool true
defaults write com.apple.Safari.SandboxBroker ShowOverlayStatusBar -bool true
defaults write com.apple.Safari.SandboxBroker WebKitMediaPlaybackAllowsInline -bool false
defaults write com.apple.Safari.SandboxBroker WebKitTabToLinksPreferenceKey -bool true

# Configure TextEdit
defaults write com.apple.TextEdit HeightInChars -int 37
defaults write com.apple.TextEdit NSFixedPitchFontSize -int 13
defaults write com.apple.TextEdit NSFontSize -int 13
defaults write com.apple.TextEdit RichText -bool false
defaults write com.apple.TextEdit WidthInChars -int 111

# Enable AirDrop over all network interfaces
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# Expand Print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Expand Save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Restore Save As… to File menu
defaults write -globalDomain NSUserKeyEquivalents -dict-add 'Save As...' '@$S'

# Configure Mac App Store
defaults write com.apple.AppStore AutoPlayVideoSetting -string "off"
defaults write com.apple.AppStore InAppReviewEnabled -bool false
defaults write com.apple.AppStore UserSetAutoPlayVideoSetting -bool true

# Disable shadows in screenshots
defaults write com.apple.screencapture "disable-shadow" -bool true

exit 0