#!/usr/bin/env sh
if [ -d "/Applications/Ice.app" ] || [ -d "$HOME/Applications/Ice.app" ]; then
    /usr/bin/killall "Ice" && /usr/bin/open -a "Ice"
else
    printf "%s\n", "Ice.app is not installed. Exiting..."
fi
